    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGraphique;

import Controleur.Controleur;
import Controleur.CtrlNouvellePartie;
import bataillenavale.Direction;
import java.awt.Color;
import java.awt.event.MouseEvent;
import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 * JPanel page nouvelle partie
 * @author gounonj
 */
public class PageNouvellePartie extends javax.swing.JPanel {

    /**
     * Creates new form PagePartieJoue
     */
    public PageNouvellePartie() {
        initComponents();
        //initialise la grille qui va permettre de placer les bateaux
        initGrille();
        
    }

     private void initGrille() {
         for(int i=0; i<=99; i++){
             final int j = i;
             jPanelTab[i] = new JPanel();
             jPanelTab[i].setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
             jPanelTab[i].setBounds(i%10*30+400, i/10*30+170, 30, 30);
             // jPanelTab[i].setBounds(300, 300, 30, 30);
             jPanelTab[i].addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {                        
                        jPanelMouseClicked(evt, jPanelTab[j],j);
                    }
                });
                     
             jPanelTab[i].setVisible(true);
             this.add(jPanelTab[i]);
             
             this.revalidate();
         }
        
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel102 = new javax.swing.JLabel();
        bateauText = new javax.swing.JLabel();
        nouvellePartie = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nord = new javax.swing.JRadioButton();
        est = new javax.swing.JRadioButton();
        sud = new javax.swing.JRadioButton();
        ouest = new javax.swing.JRadioButton();
        selectionEscorteur1 = new javax.swing.JButton();
        selectionDestroyer = new javax.swing.JButton();
        selectionEscorteur2 = new javax.swing.JButton();
        bateauText1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        valider = new javax.swing.JButton();
        annuler = new javax.swing.JButton();

        jLabel102.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel102.setText("Choisir l'orientation :");

        bateauText.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        bateauText.setText("Choisissez le bateau à placer");
        bateauText.setOpaque(true);

        nouvellePartie.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        nouvellePartie.setText("Nouvelle Partie");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMaximumSize(new java.awt.Dimension(80, 80));
        jPanel1.setMinimumSize(new java.awt.Dimension(80, 80));
        jPanel1.setPreferredSize(new java.awt.Dimension(80, 80));

        buttonGroup1.add(nord);
        nord.setText("Nord");
        nord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nordActionPerformed(evt);
            }
        });

        buttonGroup1.add(est);
        est.setText("Est");
        est.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estActionPerformed(evt);
            }
        });

        buttonGroup1.add(sud);
        sud.setText("Sud");
        sud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sudActionPerformed(evt);
            }
        });

        buttonGroup1.add(ouest);
        ouest.setText("Ouest");
        ouest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ouestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nord)
                    .addComponent(est)
                    .addComponent(sud)
                    .addComponent(ouest)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(nord)
                .addGap(6, 6, 6)
                .addComponent(est)
                .addGap(6, 6, 6)
                .addComponent(sud)
                .addGap(6, 6, 6)
                .addComponent(ouest))
        );

        selectionEscorteur1.setText("Escorteur 1");
        selectionEscorteur1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectionEscorteur1ActionPerformed(evt);
            }
        });

        selectionDestroyer.setText("Destroyer");
        selectionDestroyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectionDestroyerActionPerformed(evt);
            }
        });

        selectionEscorteur2.setText("Escorteur 2");
        selectionEscorteur2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectionEscorteur2ActionPerformed(evt);
            }
        });

        bateauText1.setFont(new java.awt.Font("DejaVu Sans", 1, 16)); // NOI18N
        bateauText1.setText("Placez vos bateaux !");
        bateauText1.setOpaque(true);

        jLabel1.setText("Vous pouvez choisir de placer 1 ou 2 bateaux escorteur.");

        valider.setText("Valider");
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });

        annuler.setText("Annuler");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(nouvellePartie, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(bateauText1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(bateauText, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(selectionDestroyer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(selectionEscorteur1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(annuler)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valider, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addComponent(jLabel102, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(selectionEscorteur2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nouvellePartie, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(bateauText1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bateauText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(selectionDestroyer)
                .addGap(1, 1, 1)
                .addComponent(selectionEscorteur1)
                .addGap(1, 1, 1)
                .addComponent(selectionEscorteur2)
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel102)
                .addGap(13, 13, 13)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valider)
                    .addComponent(annuler))
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nordActionPerformed
        Controleur.getInstance().getCtrlNouvellePartie().nordAction();
    }//GEN-LAST:event_nordActionPerformed

    private void sudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sudActionPerformed
        Controleur.getInstance().getCtrlNouvellePartie().sudAction();
    }//GEN-LAST:event_sudActionPerformed

    private void estActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estActionPerformed
        Controleur.getInstance().getCtrlNouvellePartie().estdAction();
    }//GEN-LAST:event_estActionPerformed

    private void ouestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ouestActionPerformed
        Controleur.getInstance().getCtrlNouvellePartie().ouestAction();
    }//GEN-LAST:event_ouestActionPerformed

    private void selectionDestroyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectionDestroyerActionPerformed
        Controleur.getInstance().getCtrlNouvellePartie().selectionDestroyer(this);
    }//GEN-LAST:event_selectionDestroyerActionPerformed

    private void selectionEscorteur1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectionEscorteur1ActionPerformed
        Controleur.getInstance().getCtrlNouvellePartie().selectionEscorteur1(this);
    }//GEN-LAST:event_selectionEscorteur1ActionPerformed

    private void selectionEscorteur2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectionEscorteur2ActionPerformed
        Controleur.getInstance().getCtrlNouvellePartie().selectionEscorteur2(this);
    }//GEN-LAST:event_selectionEscorteur2ActionPerformed

    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed
        Controleur.getInstance().getCtrlNouvellePartie().valider(this);        
    }//GEN-LAST:event_validerActionPerformed

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        Interface.getInstance().setPageJoueur();
    }//GEN-LAST:event_annulerActionPerformed

    public void enabledBouton(JButton bouton){
        bouton.setEnabled(false);
    }
    
    private void jPanelMouseClicked(MouseEvent evt, JPanel jPanel, int index) {
        Controleur.getInstance().getCtrlNouvellePartie().panelClicked(this,index);        
    }
    
    public JButton getDestroyer(){
        return selectionDestroyer;
    }
    
    public JButton getEscorteur1(){
        return selectionEscorteur1;
    }
    
    public JButton getEscorteur2(){
        return selectionEscorteur2;
    }

    public JPanel getJPanelTab(int index) {
        return jPanelTab[index];
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annuler;
    private javax.swing.JLabel bateauText;
    private javax.swing.JLabel bateauText1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton est;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton nord;
    private javax.swing.JLabel nouvellePartie;
    private javax.swing.JRadioButton ouest;
    private javax.swing.JButton selectionDestroyer;
    private javax.swing.JButton selectionEscorteur1;
    private javax.swing.JButton selectionEscorteur2;
    private javax.swing.JRadioButton sud;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables
    private JPanel jPanelTab[] = new JPanel[100];

    
    
   
}
