/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGraphique;

import Controleur.Controleur;
import javax.swing.JInternalFrame;
import javax.swing.JTextField;

/**
 * JPanel page accueil 
 * @author gounonj
 */
public class PageAccueil extends javax.swing.JPanel {
    

    /**
     * Creates new form PageAccueil
     */
    public PageAccueil() {        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pseudo = new javax.swing.JTextField();
        inscription = new javax.swing.JButton();
        connexion = new javax.swing.JButton();
        labelPseudo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));

        inscription.setText("Inscription");
        inscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscriptionActionPerformed(evt);
            }
        });

        connexion.setText("Connexion");
        connexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connexionActionPerformed(evt);
            }
        });

        labelPseudo.setText("Pseudo :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addComponent(labelPseudo)
                .addGap(12, 12, 12)
                .addComponent(pseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(connexion)
                .addGap(18, 18, 18)
                .addComponent(inscription)
                .addGap(180, 180, 180))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(labelPseudo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(pseudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(connexion)
                    .addComponent(inscription))
                .addGap(550, 550, 550))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Recupere l'action sur le bouton inscription et envoie l'information au controleur
     * @param evt 
     */
    private void inscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscriptionActionPerformed
        Controleur.getInstance().getCtrlAccueil().inscription();       
    }//GEN-LAST:event_inscriptionActionPerformed

    
    /**
     * Recupere l'action sur le bouton connexion et envoie l'information au controleur
     * @param evt 
     */
    private void connexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connexionActionPerformed
        Controleur.getInstance().getCtrlAccueil().connexion(this);
    }//GEN-LAST:event_connexionActionPerformed

    /**
     * On recupere le pseudo renseigné dans le JTextField
     * @return 
     */
    public JTextField getPseudo(){
        return this.pseudo;
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connexion;
    private javax.swing.JButton inscription;
    private javax.swing.JLabel labelPseudo;
    private javax.swing.JTextField pseudo;
    // End of variables declaration//GEN-END:variables

    
}
